use anyhow::{bail, Context, Result};
use clap::Parser;
use futures_util::{SinkExt, StreamExt};
use speech_core_protocol::{
    frame_duration_samples, now_mono_ns, AudioFrame, AudioFrameHeader, ClockDomain, ControlMessage,
    PcmFormat, SourceKind, TimestampProvenance, TimestampQuality,
};
use std::path::PathBuf;
use std::time::Duration;
use tokio::time::{interval, MissedTickBehavior};
use tokio_tungstenite::connect_async;
use tokio_tungstenite::tungstenite::Message;
use uuid::Uuid;

#[derive(Debug, Parser)]
#[command(author, version, about = "stream a wav file into speech-core daemon")]
struct Args {
    /// Websocket URL for daemon audio ingress.
    #[arg(
        long,
        default_value = "ws://127.0.0.1:8765/ws/audio-ingress",
        env = "SPEECH_CORE_WS_URL"
    )]
    url: String,

    /// Input wav file. Must be 16 kHz mono PCM16 or f32.
    wav: PathBuf,

    /// Stable adapter id to place in frame headers.
    #[arg(long, default_value = "file-adapter", env = "SPEECH_CORE_ADAPTER_ID")]
    adapter_id: String,

    /// Stream id to place in frame headers.
    #[arg(long, default_value = "file.replay", env = "SPEECH_CORE_STREAM_ID")]
    stream_id: String,

    /// Stream session id. Generated by default.
    #[arg(long, env = "SPEECH_CORE_STREAM_SESSION_ID")]
    stream_session_id: Option<String>,

    /// Frame duration in milliseconds.
    #[arg(long, default_value_t = 20)]
    frame_ms: u32,

    /// Pace frames in realtime instead of sending as fast as possible.
    #[arg(long)]
    realtime: bool,

    /// Append this many milliseconds of silence after the wav.
    #[arg(long, default_value_t = 1200)]
    append_silence_ms: u32,

    /// Keep the websocket open this many milliseconds after all samples are sent.
    ///
    /// Useful when testing realtime detector latency: if this is zero, connection teardown can
    /// trigger session-end silence flushes that are not representative of a still-open microphone
    /// stream.
    #[arg(long, default_value_t = 0)]
    hold_open_ms: u32,
}

#[tokio::main]
async fn main() -> Result<()> {
    let args = Args::parse();
    if args.frame_ms == 0 {
        bail!("--frame-ms must be greater than zero");
    }

    let (mut samples, format) = load_wav(&args.wav)?;
    let silence_samples = (u64::from(args.append_silence_ms) * 16_000 / 1_000) as usize;
    samples.resize(samples.len() + silence_samples, 0.0);

    let stream_session_id = args
        .stream_session_id
        .clone()
        .unwrap_or_else(|| Uuid::new_v4().to_string());
    let provenance = TimestampProvenance::same_clock(
        "file-adapter:synthetic-monotonic",
        ClockDomain::SyntheticAdapter,
        TimestampQuality::SyntheticScheduled,
    );

    let (mut ws, _) = connect_async(&args.url)
        .await
        .with_context(|| format!("connecting to {}", args.url))?;
    let hello = ControlMessage::Hello {
        adapter_id: args.adapter_id.clone(),
        stream_id: args.stream_id.clone(),
        stream_session_id: stream_session_id.clone(),
        source_kind: SourceKind::File,
        sample_rate_hz: 16_000,
        channels: 1,
        format,
        timestamp_provenance: provenance.clone(),
        adapter_hello_send_mono_ns: now_mono_ns(),
    };
    ws.send(Message::Text(serde_json::to_string(&hello)?))
        .await?;

    let samples_per_frame = frame_duration_samples(16_000, args.frame_ms) as usize;
    let mut seq = 0_u64;
    let mut source_sample_start = 0_u64;
    let mut ticker = interval(Duration::from_millis(args.frame_ms as u64));
    ticker.set_missed_tick_behavior(MissedTickBehavior::Delay);

    for chunk in samples.chunks(samples_per_frame) {
        if args.realtime {
            ticker.tick().await;
        }
        let sample_count = chunk.len() as u32;
        let capture_ns = now_mono_ns();
        let payload = encode_payload(chunk, format);
        let frame = AudioFrame::new(
            AudioFrameHeader {
                stream_id: args.stream_id.clone(),
                stream_session_id: stream_session_id.clone(),
                adapter_id: args.adapter_id.clone(),
                source_kind: SourceKind::File,
                seq,
                format,
                sample_rate_hz: 16_000,
                channels: 1,
                source_sample_start,
                sample_count,
                source_capture_mono_ns: capture_ns,
                adapter_send_mono_ns: now_mono_ns(),
                timestamp_provenance: provenance.clone(),
                preceding_source_gap: None,
            },
            payload,
        )?;
        ws.send(Message::Binary(frame.encode()?)).await?;
        drain_available_text(&mut ws).await?;
        seq = seq.saturating_add(1);
        source_sample_start = source_sample_start.saturating_add(u64::from(sample_count));
    }

    if args.hold_open_ms > 0 {
        tokio::time::sleep(Duration::from_millis(args.hold_open_ms as u64)).await;
        drain_available_text(&mut ws).await?;
    }

    ws.close(None).await.ok();
    eprintln!("sent {seq} frames, {source_sample_start} samples, session={stream_session_id}");
    Ok(())
}

fn load_wav(path: &PathBuf) -> Result<(Vec<f32>, PcmFormat)> {
    let mut reader =
        hound::WavReader::open(path).with_context(|| format!("opening wav {}", path.display()))?;
    let spec = reader.spec();
    if spec.sample_rate != 16_000 {
        bail!("expected 16 kHz wav, got {} Hz", spec.sample_rate);
    }
    if spec.channels != 1 {
        bail!("expected mono wav, got {} channels", spec.channels);
    }
    match spec.sample_format {
        hound::SampleFormat::Float => {
            let samples = reader.samples::<f32>().collect::<Result<Vec<_>, _>>()?;
            Ok((samples, PcmFormat::PcmF32Le))
        }
        hound::SampleFormat::Int if spec.bits_per_sample == 16 => {
            let samples = reader
                .samples::<i16>()
                .map(|s| s.map(|v| f32::from(v) / 32768.0))
                .collect::<Result<Vec<_>, _>>()?;
            Ok((samples, PcmFormat::PcmS16Le))
        }
        hound::SampleFormat::Int => bail!("only PCM16 integer wav is supported"),
    }
}

fn encode_payload(samples: &[f32], format: PcmFormat) -> Vec<u8> {
    match format {
        PcmFormat::PcmF32Le => samples.iter().flat_map(|s| s.to_le_bytes()).collect(),
        PcmFormat::PcmS16Le => samples
            .iter()
            .flat_map(|s| {
                let clamped = s.clamp(-1.0, 1.0);
                let v = (clamped * 32767.0).round() as i16;
                v.to_le_bytes()
            })
            .collect(),
    }
}

async fn drain_available_text(
    ws: &mut tokio_tungstenite::WebSocketStream<
        tokio_tungstenite::MaybeTlsStream<tokio::net::TcpStream>,
    >,
) -> Result<()> {
    loop {
        match tokio::time::timeout(Duration::from_millis(1), ws.next()).await {
            Ok(Some(Ok(Message::Text(_)))) => {}
            Ok(Some(Ok(Message::Binary(_)))) => {}
            Ok(Some(Ok(Message::Ping(payload)))) => ws.send(Message::Pong(payload)).await?,
            Ok(Some(Ok(Message::Close(_)))) | Ok(None) => break,
            Ok(Some(Ok(_))) => {}
            Ok(Some(Err(err))) => return Err(err.into()),
            Err(_) => break,
        }
    }
    Ok(())
}
