use bytes::{Buf, BufMut, BytesMut};
use serde::{Deserialize, Serialize};
use std::fmt;
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use thiserror::Error;

const MAGIC: &[u8; 4] = b"SCF1";
const VERSION: u8 = 1;
const HEADER_FIXED_LEN: usize = 4 + 1 + 4;
const MAX_JSON_HEADER_LEN: usize = 64 * 1024;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SourceKind {
    Mic,
    Discord,
    Browser,
    File,
    Synthetic,
    Other,
}

impl fmt::Display for SourceKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SourceKind::Mic => write!(f, "mic"),
            SourceKind::Discord => write!(f, "discord"),
            SourceKind::Browser => write!(f, "browser"),
            SourceKind::File => write!(f, "file"),
            SourceKind::Synthetic => write!(f, "synthetic"),
            SourceKind::Other => write!(f, "other"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PcmFormat {
    #[serde(rename = "pcm_s16le")]
    PcmS16Le,
    #[serde(rename = "pcm_f32le")]
    PcmF32Le,
}

impl PcmFormat {
    pub fn bytes_per_sample(self) -> u32 {
        match self {
            PcmFormat::PcmS16Le => 2,
            PcmFormat::PcmF32Le => 4,
        }
    }
}

impl fmt::Display for PcmFormat {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            PcmFormat::PcmS16Le => write!(f, "pcm_s16le"),
            PcmFormat::PcmF32Le => write!(f, "pcm_f32le"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ClockDomain {
    HostMonotonic,
    CpalInputStream,
    SyntheticAdapter,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TimestampQuality {
    /// Source/device capture timestamp, represented in the adapter clock domain.
    SourceCapture,
    /// Adapter callback receive time; useful for ordering but not true device-capture latency.
    CallbackReceive,
    /// Synthetic scheduler timestamp generated by the adapter.
    SyntheticScheduled,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TimestampSemantics {
    /// `source_capture_mono_ns` denotes the first sample in the frame.
    FirstSample,
    /// Reserved for sources that can only stamp the end of a frame.
    FrameEnd,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ClockComparability {
    /// Adapter timestamps and daemon timestamps are known to share the same monotonic clock.
    SameClock,
    /// Adapter supplied an estimated daemon offset and uncertainty.
    EstimatedOffset,
    /// No safe cross-clock arithmetic is available. This is the default for cross-host adapters.
    Uncalibrated,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TimestampProvenance {
    pub adapter_clock_id: String,
    pub adapter_clock_domain: ClockDomain,
    pub timestamp_quality: TimestampQuality,
    pub timestamp_semantics: TimestampSemantics,
    pub clock_comparability: ClockComparability,
    /// Estimated offset where `daemon_ns ~= adapter_ns + offset_ns`.
    pub estimated_daemon_offset_ns: Option<i64>,
    pub estimated_offset_uncertainty_ns: Option<u64>,
}

impl TimestampProvenance {
    pub fn uncalibrated(
        adapter_clock_id: impl Into<String>,
        adapter_clock_domain: ClockDomain,
        timestamp_quality: TimestampQuality,
    ) -> Self {
        Self {
            adapter_clock_id: adapter_clock_id.into(),
            adapter_clock_domain,
            timestamp_quality,
            timestamp_semantics: TimestampSemantics::FirstSample,
            clock_comparability: ClockComparability::Uncalibrated,
            estimated_daemon_offset_ns: None,
            estimated_offset_uncertainty_ns: None,
        }
    }

    pub fn same_clock(
        adapter_clock_id: impl Into<String>,
        adapter_clock_domain: ClockDomain,
        timestamp_quality: TimestampQuality,
    ) -> Self {
        Self {
            adapter_clock_id: adapter_clock_id.into(),
            adapter_clock_domain,
            timestamp_quality,
            timestamp_semantics: TimestampSemantics::FirstSample,
            clock_comparability: ClockComparability::SameClock,
            estimated_daemon_offset_ns: None,
            estimated_offset_uncertainty_ns: None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SourceSampleGap {
    pub dropped_samples: u64,
    pub dropped_frames_estimate: u64,
    pub adapter_total_dropped_samples: u64,
    pub adapter_total_dropped_buffers: u64,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AudioFrameHeader {
    pub stream_id: String,
    pub stream_session_id: String,
    pub adapter_id: String,
    pub source_kind: SourceKind,
    pub seq: u64,
    pub format: PcmFormat,
    pub sample_rate_hz: u32,
    pub channels: u16,
    pub source_sample_start: u64,
    pub sample_count: u32,
    /// Adapter-clock timestamp for the first sample in this frame unless provenance says otherwise.
    pub source_capture_mono_ns: u64,
    /// Adapter-clock timestamp when this frame was serialized/sent.
    pub adapter_send_mono_ns: u64,
    pub timestamp_provenance: TimestampProvenance,
    pub preceding_source_gap: Option<SourceSampleGap>,
}

impl AudioFrameHeader {
    pub fn expected_payload_len(&self) -> Option<usize> {
        let samples = self.sample_count.checked_mul(self.channels as u32)?;
        let bytes = samples.checked_mul(self.format.bytes_per_sample())?;
        usize::try_from(bytes).ok()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AudioFrame {
    pub header: AudioFrameHeader,
    pub payload: Vec<u8>,
}

impl AudioFrame {
    pub fn new(header: AudioFrameHeader, payload: Vec<u8>) -> Result<Self, ProtocolError> {
        let frame = Self { header, payload };
        frame.validate_payload_len()?;
        Ok(frame)
    }

    pub fn validate_payload_len(&self) -> Result<(), ProtocolError> {
        let expected = self
            .header
            .expected_payload_len()
            .ok_or(ProtocolError::PayloadLengthOverflow)?;
        if self.payload.len() != expected {
            return Err(ProtocolError::PayloadLengthMismatch {
                expected,
                actual: self.payload.len(),
            });
        }
        Ok(())
    }

    pub fn encode(&self) -> Result<Vec<u8>, ProtocolError> {
        self.validate_payload_len()?;
        let header_json = serde_json::to_vec(&self.header)?;
        if header_json.len() > MAX_JSON_HEADER_LEN {
            return Err(ProtocolError::HeaderTooLarge(header_json.len()));
        }

        let mut out = Vec::with_capacity(HEADER_FIXED_LEN + header_json.len() + self.payload.len());
        out.extend_from_slice(MAGIC);
        out.put_u8(VERSION);
        out.put_u32(header_json.len() as u32);
        out.extend_from_slice(&header_json);
        out.extend_from_slice(&self.payload);
        Ok(out)
    }

    pub fn decode(bytes: &[u8]) -> Result<Self, ProtocolError> {
        if bytes.len() < HEADER_FIXED_LEN {
            return Err(ProtocolError::FrameTooShort(bytes.len()));
        }

        let mut cursor = bytes;
        let mut magic = [0u8; 4];
        cursor.copy_to_slice(&mut magic);
        if &magic != MAGIC {
            return Err(ProtocolError::BadMagic(magic));
        }

        let version = cursor.get_u8();
        if version != VERSION {
            return Err(ProtocolError::UnsupportedVersion(version));
        }

        let header_len = cursor.get_u32() as usize;
        if header_len > MAX_JSON_HEADER_LEN {
            return Err(ProtocolError::HeaderTooLarge(header_len));
        }
        if cursor.remaining() < header_len {
            return Err(ProtocolError::TruncatedHeader {
                header_len,
                remaining: cursor.remaining(),
            });
        }

        let mut header_bytes = BytesMut::with_capacity(header_len);
        header_bytes.extend_from_slice(&cursor[..header_len]);
        cursor.advance(header_len);

        let header: AudioFrameHeader = serde_json::from_slice(&header_bytes)?;
        let frame = Self {
            header,
            payload: cursor.to_vec(),
        };
        frame.validate_payload_len()?;
        Ok(frame)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ControlMessage {
    Hello {
        adapter_id: String,
        stream_id: String,
        stream_session_id: String,
        source_kind: SourceKind,
        sample_rate_hz: u32,
        channels: u16,
        format: PcmFormat,
        timestamp_provenance: TimestampProvenance,
        adapter_hello_send_mono_ns: u64,
    },
    Ping {
        adapter_id: String,
        stream_session_id: String,
        mono_ns: u64,
    },
    Drain {
        stream_id: String,
        stream_session_id: String,
        reason: Option<String>,
    },
    SubscribeEvents {
        stream_id: Option<String>,
        stream_session_id: Option<String>,
        event: Option<String>,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerEvent {
    StreamStart(StreamStart),
    HelloAck(HelloAck),
    AudioFrameIngested(AudioFrameIngested),
    AudioGap(AudioGap),
    AudioSampleGap(AudioSampleGap),
    AudioDrop {
        stream_id: String,
        stream_session_id: String,
        seq: u64,
        reason: String,
    },
    Error {
        message: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct StreamStart {
    pub stream_id: String,
    pub stream_session_id: String,
    pub adapter_id: String,
    pub source_kind: SourceKind,
    pub sample_rate_hz: u32,
    pub channels: u16,
    pub format: PcmFormat,
    pub timestamp_provenance: TimestampProvenance,
    pub daemon_mono_ns: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct HelloAck {
    pub stream_id: String,
    pub stream_session_id: String,
    pub adapter_id: String,
    pub daemon_receive_mono_ns: u64,
    pub daemon_send_mono_ns: u64,
    pub adapter_hello_send_mono_ns: u64,
    pub clock_comparability: ClockComparability,
    pub estimated_offset_uncertainty_ns: Option<u64>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum LatencyStatus {
    SameClock,
    EstimatedOffset,
    Uncalibrated,
    TimestampQualityInsufficient,
    TimestampSemanticsUnsupported,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LatencyMeasurement {
    pub value_ms: Option<f64>,
    pub status: LatencyStatus,
    pub uncertainty_ms: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AudioFrameIngested {
    pub stream_id: String,
    pub stream_session_id: String,
    pub adapter_id: String,
    pub source_kind: SourceKind,
    pub seq: u64,
    pub sample_start: u64,
    pub sample_count: u32,
    pub source_capture_mono_ns: u64,
    pub adapter_send_mono_ns: u64,
    pub timestamp_provenance: TimestampProvenance,
    pub ingress_receive_mono_ns: u64,
    pub ingress_queue_enter_mono_ns: u64,
    pub ingress_queue_exit_mono_ns: u64,
    /// Actual queue depth. Transport v1 has no downstream queue yet, so this is 0.
    pub ingress_queue_depth_frames: usize,
    pub frames_seen_in_session: u64,
    pub capture_to_ingress: LatencyMeasurement,
    pub adapter_send_to_ingress: LatencyMeasurement,
    pub sequence_gap: Option<i64>,
    pub sample_gap: Option<AudioSampleGap>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AudioGap {
    pub stream_id: String,
    pub stream_session_id: String,
    pub adapter_id: String,
    pub expected_seq: u64,
    pub observed_seq: u64,
    pub missing_frames: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AudioSampleGap {
    pub stream_id: String,
    pub stream_session_id: String,
    pub adapter_id: String,
    pub expected_sample_start: u64,
    pub observed_sample_start: u64,
    pub delta_samples: i64,
    pub declared_source_gap: Option<SourceSampleGap>,
}

#[derive(Debug, Error)]
pub enum ProtocolError {
    #[error("frame too short: {0} bytes")]
    FrameTooShort(usize),
    #[error("bad magic: {0:?}")]
    BadMagic([u8; 4]),
    #[error("unsupported protocol version: {0}")]
    UnsupportedVersion(u8),
    #[error("json header too large: {0} bytes")]
    HeaderTooLarge(usize),
    #[error("truncated header: wanted {header_len} bytes, only {remaining} remaining")]
    TruncatedHeader { header_len: usize, remaining: usize },
    #[error("payload length overflow")]
    PayloadLengthOverflow,
    #[error("payload length mismatch: expected {expected} bytes, got {actual}")]
    PayloadLengthMismatch { expected: usize, actual: usize },
    #[error("json error: {0}")]
    Json(#[from] serde_json::Error),
}

pub fn now_mono_ns() -> u64 {
    monotonic_duration().as_nanos().min(u128::from(u64::MAX)) as u64
}

pub fn monotonic_duration() -> Duration {
    #[cfg(target_os = "linux")]
    {
        let mut ts = libc::timespec {
            tv_sec: 0,
            tv_nsec: 0,
        };
        let rc = unsafe { libc::clock_gettime(libc::CLOCK_MONOTONIC, &mut ts) };
        if rc == 0 {
            return Duration::new(ts.tv_sec as u64, ts.tv_nsec as u32);
        }
    }

    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
}

pub fn ns_delta_to_ms(later_ns: u64, earlier_ns: u64) -> f64 {
    later_ns.saturating_sub(earlier_ns) as f64 / 1_000_000.0
}

pub fn capture_to_ingress_latency(
    daemon_ns: u64,
    source_capture_ns: u64,
    provenance: &TimestampProvenance,
) -> LatencyMeasurement {
    if provenance.clock_comparability == ClockComparability::Uncalibrated {
        return uncalibrated_latency();
    }
    if provenance.timestamp_quality != TimestampQuality::SourceCapture {
        return LatencyMeasurement {
            value_ms: None,
            status: LatencyStatus::TimestampQualityInsufficient,
            uncertainty_ms: None,
        };
    }
    if provenance.timestamp_semantics != TimestampSemantics::FirstSample {
        return LatencyMeasurement {
            value_ms: None,
            status: LatencyStatus::TimestampSemanticsUnsupported,
            uncertainty_ms: None,
        };
    }
    cross_clock_latency(daemon_ns, source_capture_ns, provenance)
}

pub fn adapter_send_to_ingress_latency(
    daemon_ns: u64,
    adapter_send_ns: u64,
    provenance: &TimestampProvenance,
) -> LatencyMeasurement {
    cross_clock_latency(daemon_ns, adapter_send_ns, provenance)
}

pub fn cross_clock_latency(
    daemon_ns: u64,
    adapter_ns: u64,
    provenance: &TimestampProvenance,
) -> LatencyMeasurement {
    match provenance.clock_comparability {
        ClockComparability::SameClock => LatencyMeasurement {
            value_ms: Some(ns_delta_to_ms(daemon_ns, adapter_ns)),
            status: LatencyStatus::SameClock,
            uncertainty_ms: None,
        },
        ClockComparability::EstimatedOffset => match provenance.estimated_daemon_offset_ns {
            Some(offset) => {
                let adjusted_adapter_ns = if offset >= 0 {
                    adapter_ns.saturating_add(offset as u64)
                } else {
                    adapter_ns.saturating_sub(offset.unsigned_abs())
                };
                LatencyMeasurement {
                    value_ms: Some(ns_delta_to_ms(daemon_ns, adjusted_adapter_ns)),
                    status: LatencyStatus::EstimatedOffset,
                    uncertainty_ms: provenance
                        .estimated_offset_uncertainty_ns
                        .map(|ns| ns as f64 / 1_000_000.0),
                }
            }
            None => uncalibrated_latency(),
        },
        ClockComparability::Uncalibrated => uncalibrated_latency(),
    }
}

fn uncalibrated_latency() -> LatencyMeasurement {
    LatencyMeasurement {
        value_ms: None,
        status: LatencyStatus::Uncalibrated,
        uncertainty_ms: None,
    }
}

pub fn frame_duration_samples(sample_rate_hz: u32, frame_ms: u32) -> u32 {
    sample_rate_hz.saturating_mul(frame_ms) / 1000
}

pub fn frame_payload_len(sample_count: u32, channels: u16, format: PcmFormat) -> Option<usize> {
    let samples = sample_count.checked_mul(channels as u32)?;
    let bytes = samples.checked_mul(format.bytes_per_sample())?;
    usize::try_from(bytes).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn header() -> AudioFrameHeader {
        AudioFrameHeader {
            stream_id: "stream".into(),
            stream_session_id: "session".into(),
            adapter_id: "adapter".into(),
            source_kind: SourceKind::Mic,
            seq: 42,
            format: PcmFormat::PcmS16Le,
            sample_rate_hz: 16_000,
            channels: 1,
            source_sample_start: 13_440,
            sample_count: 320,
            source_capture_mono_ns: 1_000,
            adapter_send_mono_ns: 2_000,
            timestamp_provenance: TimestampProvenance::uncalibrated(
                "host:test:monotonic",
                ClockDomain::HostMonotonic,
                TimestampQuality::SourceCapture,
            ),
            preceding_source_gap: Some(SourceSampleGap {
                dropped_samples: 320,
                dropped_frames_estimate: 1,
                adapter_total_dropped_samples: 320,
                adapter_total_dropped_buffers: 1,
                reason: "test".into(),
            }),
        }
    }

    #[test]
    fn frame_round_trips_with_payload_and_provenance() {
        let frame = AudioFrame::new(header(), vec![0; 640]).unwrap();
        let encoded = frame.encode().unwrap();
        let decoded = AudioFrame::decode(&encoded).unwrap();
        assert_eq!(decoded, frame);
        assert_eq!(
            decoded.header.timestamp_provenance.timestamp_semantics,
            TimestampSemantics::FirstSample
        );
        assert_eq!(
            decoded.header.preceding_source_gap.unwrap().dropped_samples,
            320
        );
    }

    #[test]
    fn uncalibrated_cross_host_latency_is_unknown() {
        let provenance = TimestampProvenance::uncalibrated(
            "host:sfnix:monotonic",
            ClockDomain::HostMonotonic,
            TimestampQuality::SourceCapture,
        );
        let latency = cross_clock_latency(10_000_000, 1_000_000, &provenance);
        assert_eq!(latency.value_ms, None);
        assert_eq!(latency.status, LatencyStatus::Uncalibrated);
    }

    #[test]
    fn same_clock_source_capture_latency_is_computed() {
        let provenance = TimestampProvenance::same_clock(
            "host:sfub:monotonic",
            ClockDomain::HostMonotonic,
            TimestampQuality::SourceCapture,
        );
        let latency = capture_to_ingress_latency(11_000_000, 1_000_000, &provenance);
        assert_eq!(latency.value_ms, Some(10.0));
        assert_eq!(latency.status, LatencyStatus::SameClock);
    }

    #[test]
    fn capture_latency_requires_source_capture_quality_when_clocks_are_comparable() {
        let provenance = TimestampProvenance::same_clock(
            "host:sfub:monotonic",
            ClockDomain::HostMonotonic,
            TimestampQuality::CallbackReceive,
        );
        let latency = capture_to_ingress_latency(11_000_000, 1_000_000, &provenance);
        assert_eq!(latency.value_ms, None);
        assert_eq!(latency.status, LatencyStatus::TimestampQualityInsufficient);
    }

    #[test]
    fn adapter_send_latency_does_not_require_source_capture_quality() {
        let provenance = TimestampProvenance::same_clock(
            "host:sfub:monotonic",
            ClockDomain::HostMonotonic,
            TimestampQuality::CallbackReceive,
        );
        let latency = adapter_send_to_ingress_latency(11_000_000, 1_000_000, &provenance);
        assert_eq!(latency.value_ms, Some(10.0));
        assert_eq!(latency.status, LatencyStatus::SameClock);
    }

    #[test]
    fn rejects_wrong_payload_size() {
        let err = AudioFrame::new(header(), vec![0; 12]).unwrap_err();
        assert!(matches!(err, ProtocolError::PayloadLengthMismatch { .. }));
    }

    #[test]
    fn computes_frame_payload_len() {
        assert_eq!(frame_payload_len(320, 2, PcmFormat::PcmF32Le), Some(2560));
    }
}
